# Numpy Paketi

In [7]:
import numpy as np

In [3]:
liste = [5,8,78,96]

In [20]:
not1 = np.array([12,78,78,12,45])
not2 = np.array([12,58,41,12,45])

In [21]:
type(not1)

numpy.ndarray

In [26]:
donem_sonu_notu = not1 *0.3 + not2*0.7
donem_sonu_notu

array([12. , 64. , 52.1, 12. , 45. ])

In [28]:
donem_sonu_notu >= 45

array([False,  True,  True, False,  True])

In [30]:
donem_sonu_notu[donem_sonu_notu >= 45]

3

In [127]:
def sonuc(notu):
    if notu < 45:
        return "Kaldı"
    else:
        return "Geçti"

In [131]:
sonuc_vectorized = np.vectorize(sonuc)

In [133]:
sonuc_listesi = np.random.randint(0,100, 1000)
sonuc_listesi

array([19, 13, 50, 85, 21, 66, 93, 90, 92, 55, 15, 58, 32, 55, 81,  3, 67,
       36, 32, 44, 85, 85, 94, 74, 11, 97, 48, 66, 87,  5, 82, 47, 42, 19,
       94, 89, 74, 41, 51, 35, 16, 19, 25, 51, 48, 33, 87, 57, 24, 75, 87,
       56, 65, 73, 37, 74, 45, 61, 83, 57,  5, 54, 42, 97, 19, 55,  5, 64,
       58, 53, 10,  2, 90, 82, 92, 30,  8, 88, 50, 77, 65, 31, 59, 22, 66,
       72, 93, 75, 64, 61, 43, 94, 50, 78, 25, 27, 45, 88, 53, 29, 61,  6,
       10, 76, 25,  2, 81, 58, 77, 40, 17, 63, 93, 44, 64, 92, 83, 12, 71,
        6, 20, 67, 28, 30, 47, 43, 53, 48, 59, 59, 68, 88, 92, 13, 65, 78,
       65, 58, 52, 64, 80, 68, 44, 41, 64, 67, 39, 91, 79,  8, 59, 64, 19,
       63, 15, 53, 77, 36,  8, 58, 99, 14, 55, 48, 54, 52, 12, 45, 87,  7,
       38, 82, 60, 86, 35, 58, 66, 54, 56, 95, 54, 53, 79, 52, 68, 91, 81,
       93, 90,  6, 70, 57, 26, 97, 27, 16, 12, 36,  3, 24, 45, 72, 74, 60,
       37, 89, 21,  5, 29, 46, 53, 38, 99,  1, 64,  3, 92, 24,  5,  8, 35,
       15, 42, 93, 43,  8

In [136]:
son_liste= sonuc_vectorized(sonuc_listesi)
type(son_liste)

numpy.ndarray

In [138]:
son_liste[son_liste == "Geçti"]
np.sqrt(donem_sonu_notu)

array([3.46410162, 8.        , 7.21803297, 3.46410162, 6.70820393])

In [34]:
print(np.arange(2000, 2021, 3))
np.linspace(-5,5,20)

[2000 2003 2006 2009 2012 2015 2018]


array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

In [36]:
dizi_2d = np.array([[25,54,78],[85,65,87],[0,45,79]])
dizi_2d

array([[25, 54, 78],
       [85, 65, 87],
       [ 0, 45, 79]])

In [44]:
dizi_2d[:,2]

81.33333333333333

In [51]:
dizi = np.random.randint(1,100, 40).reshape(10,4)
dizi

array([[79, 70, 25, 70],
       [ 4, 43, 60, 16],
       [95, 56, 15, 55],
       [69, 21, 39,  3],
       [58, 52, 71, 87],
       [39, 95, 39, 37],
       [81, 64, 59,  5],
       [19, 48, 14, 46],
       [53, 40, 86, 80],
       [ 7, 68, 10,  7]])

In [57]:
dizi.sum(axis=0) # 0 : Sütun 1: Satır

array([244, 123, 221, 132, 268, 210, 209, 127, 259,  92])

In [60]:
dizi.cumsum(axis = 1)

array([[ 79, 149, 174, 244],
       [  4,  47, 107, 123],
       [ 95, 151, 166, 221],
       [ 69,  90, 129, 132],
       [ 58, 110, 181, 268],
       [ 39, 134, 173, 210],
       [ 81, 145, 204, 209],
       [ 19,  67,  81, 127],
       [ 53,  93, 179, 259],
       [  7,  75,  85,  92]], dtype=int32)

In [67]:
dizi.ptp(0)

array([91, 74, 76, 84])

In [70]:
dizi2 = np.random.randint(1,100, 40).reshape(10,4)
dizi2

array([[ 7, 33, 97, 63],
       [ 9, 24, 33, 72],
       [18, 83, 60, 25],
       [32, 63, 24, 22],
       [26, 61, 70, 49],
       [55,  6, 91, 95],
       [38, 83, 84, 51],
       [88, 43, 21, 20],
       [83, 41, 55, 86],
       [92, 78, 38, 41]])

In [73]:
dizi * dizi2

array([[ 553, 2310, 2425, 4410],
       [  36, 1032, 1980, 1152],
       [1710, 4648,  900, 1375],
       [2208, 1323,  936,   66],
       [1508, 3172, 4970, 4263],
       [2145,  570, 3549, 3515],
       [3078, 5312, 4956,  255],
       [1672, 2064,  294,  920],
       [4399, 1640, 4730, 6880],
       [ 644, 5304,  380,  287]])

In [80]:
np.max(dizi[0:5,:], axis = 0)

array([95, 70, 71, 87])

In [82]:
dizi

array([[79, 70, 25, 70],
       [ 4, 43, 60, 16],
       [95, 56, 15, 55],
       [69, 21, 39,  3],
       [58, 52, 71, 87],
       [39, 95, 39, 37],
       [81, 64, 59,  5],
       [19, 48, 14, 46],
       [53, 40, 86, 80],
       [ 7, 68, 10,  7]])

In [89]:
dizi[[0,4], 0:2]

array([[79, 70],
       [58, 52]])

In [97]:
np.std(dizi[0,:])
liste1 = np.array([0,1,0,2,3,0])
liste2 = np.array([-10, 10, -10, 10, 6, 0])

In [103]:
np.mean(liste2)


1.0

In [106]:
np.corrcoef(dizi[:,0], dizi[:,1]) #(fonksiyon, metodlar)

array([[ 1.        , -0.03237583],
       [-0.03237583,  1.        ]])

In [118]:
matrix1 = np.random.randint(1,100, 24).reshape(4,6)
matrix2 = np.random.randint(1,100, 36).reshape(6,6)

In [126]:
np.concatenate((matrix1, matrix2), axis = 0)
matrix1

array([[77, 38, 50, 82, 30, 44],
       [87, 46, 38, 49, 71, 81],
       [58, 80, 40, 18, 44, 93],
       [65, 21, 70, 23, 20, 50]])