In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn import preprocessing
#from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.cluster import AgglomerativeClustering, DBSCAN, KMeans
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
from sklearn import metrics
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.svm import SVC, SVR
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor 
from sklearn.naive_bayes import GaussianNB

In [2]:
df = sns.load_dataset("diamonds")

In [3]:
df["cut"].value_counts()

Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: cut, dtype: int64

In [4]:
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
model = SVC(kernel='linear')


In [15]:
feature_select = RFE(estimator=model, n_features_to_select=1)

In [11]:
df[["color"]].value_counts()

color
G        11292
E         9797
F         9542
H         8304
D         6775
I         5422
J         2808
dtype: int64

In [12]:
df.shape

(53940, 10)

In [7]:
encoder = preprocessing.OrdinalEncoder()
encoder.fit(df[["color"]])
df[["color"]] = encoder.transform(df[["color"]])

In [21]:
df.head()

carat  cut  color  clarity  depth  table  price     x     y     z
0   0.23  2.0    1.0      3.0   61.5   55.0    326  3.95  3.98  2.43
1   0.21  3.0    1.0      2.0   59.8   61.0    326  3.89  3.84  2.31
2   0.23  1.0    1.0      4.0   56.9   65.0    327  4.05  4.07  2.31
3   0.29  3.0    5.0      5.0   62.4   58.0    334  4.20  4.23  2.63
4   0.31  1.0    6.0      3.0   63.3   58.0    335  4.34  4.35  2.75

In [8]:
encoder = preprocessing.OrdinalEncoder()
encoder.fit(df[["cut"]])
df[["cut"]] = encoder.transform(df[["cut"]])

In [9]:
encoder = preprocessing.OrdinalEncoder()
encoder.fit(df[["clarity"]])
df[["clarity"]] = encoder.transform(df[["clarity"]])


In [46]:
X = df.loc[:1000, ["carat","color","clarity","depth","table", "x","y","z"]]
y = df.loc[:1000, ["cut"]]

In [16]:
feature_select.fit(X,y)

C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A colu

RFE(estimator=SVC(kernel='linear'), n_features_to_select=1)

In [17]:
feature_select.ranking_

array([3, 8, 7, 5, 4, 9, 1, 2, 6])

In [18]:
X.columns

Index(['carat', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z'], dtype='object')

In [19]:
feature_select.support_

array([False, False, False, False, False, False,  True, False, False])

In [30]:
reg = SVC()
reg.fit(X, y)

MLPRegressor()

In [31]:
reg.predict(X)

array([[1.62856184e+00, 2.35414613e+03],
       [1.36264888e+00, 2.41352398e+03],
       [1.12957472e+00, 2.47845695e+03],
       ...,
       [9.75752471e-01, 2.53437814e+03],
       [1.60682573e+00, 2.62313740e+03],
       [1.07730910e+00, 2.44001896e+03]])

In [32]:
est = MLPRegressor()
act = ('relu','tanh')
layer_size = ((50,), (100,), (150,), (200,))
grid = GridSearchCV(estimator = est, param_grid= {'hidden_layer_sizes': layer_size, 'activation': ('relu','tanh')})

In [33]:
grid.fit(X,y)

C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't conv

C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


GridSearchCV(estimator=MLPRegressor(),
             param_grid={'activation': ('relu', 'tanh'),
                         'hidden_layer_sizes': ((50,), (100,), (150,), (200,))})

In [34]:
grid.best_params_

{'activation': 'relu', 'hidden_layer_sizes': (150,)}

In [40]:
print(grid.cv_results_)

{'mean_fit_time': array([0.82702031, 1.03580632, 1.00061178, 1.87271881, 1.08693743,
       1.54096098, 2.15942931, 2.71256599]), 'std_fit_time': array([0.08807724, 0.15675734, 0.27585125, 0.39451018, 0.11722675,
       0.19223667, 0.07875552, 0.24286213]), 'mean_score_time': array([0.00630322, 0.00780182, 0.00561705, 0.00719919, 0.00977349,
       0.00639997, 0.00860243, 0.00579896]), 'std_score_time': array([0.00269837, 0.00620333, 0.00290447, 0.00396962, 0.00728359,
       0.00349453, 0.00676931, 0.00116846]), 'param_activation': masked_array(data=['relu', 'relu', 'relu', 'relu', 'tanh', 'tanh', 'tanh',
                   'tanh'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_hidden_layer_sizes': masked_array(data=[(50,), (100,), (150,), (200,), (50,), (100,), (150,),
                   (200,)],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
    

In [50]:
est = SVC()
kern = ('rbf','linear', 'poly')
c = [1,13,5,10]
grid = GridSearchCV(estimator = est, param_grid= {'kernel': kern, 'C': c})

In [51]:
grid.fit(X,y)

C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A colu

C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A colu

C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Betul\PycharmProjects\EgitimNotlari\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 13, 5, 10],
                         'kernel': ('rbf', 'linear', 'poly')})

In [52]:
grid.cv_results_

{'mean_fit_time': array([0.0862565 , 0.22226739, 0.04160376, 0.0567976 , 0.6205029 ,
        0.05580077, 0.08729692, 0.28867083, 0.0447957 , 0.05710373,
        0.4748507 , 0.04742212]),
 'std_fit_time': array([0.03378189, 0.12033748, 0.00882114, 0.01239369, 0.14557052,
        0.0206871 , 0.02302156, 0.06088009, 0.01874612, 0.00897316,
        0.0621205 , 0.0131471 ]),
 'mean_score_time': array([0.04421959, 0.01102228, 0.00860362, 0.04959555, 0.01158738,
        0.01840477, 0.04755964, 0.00819392, 0.00892444, 0.03402209,
        0.01525559, 0.01397934]),
 'std_score_time': array([0.00870228, 0.00432625, 0.00163568, 0.0211817 , 0.00838595,
        0.0166449 , 0.02131854, 0.00342707, 0.0039507 , 0.01037858,
        0.01021498, 0.0096863 ]),
 'param_C': masked_array(data=[1, 1, 1, 13, 13, 13, 5, 5, 5, 10, 10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),

In [53]:
grid.best_params_

{'C': 13, 'kernel': 'linear'}